#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - find-latest-version                  Copyright(c) 2019 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package ea_libzip::find_latest_version;

use strict;
use warnings;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

###############
#### helpers ##
###############

sub _get_required {
    my ($http) = @_;

    my ( $version, $url, $name );

    my $res = $http->get("https://api.github.com/repos/nih-at/libzip/tags");

    my $tag_refs = ea4_tool::util::json2ref( $res->{content} );
    my $tag;

    foreach my $tag_ref ( @{$tag_refs} ) {
        if ( !defined $tag ) {
            $tag = $tag_ref;
            last;
        }

        if ( $tag_ref->{name} gt $tag->{name} ) {
            $tag = $tag_ref;
            last;
        }
    }

    die "Cannot find latest version" if !defined $tag;

    $name    = $tag->{'name'};
    $version = substr( $name, 1 );
    $version =~ s/\-/./g;
    $url  = "https://github.com/nih-at/libzip/releases/download/$name/libzip-$version.tar.gz";
    $name = "libzip-$version.tar.gz";

    return ( $version, $url, $name );
}

sub _add_sum {
    my ( $http, $hr ) = @_;

    # I could not find a way to get the sum

    return;
}

ea4_tool::util::find_latest_version( \&_get_required, \&_add_sum ) if !caller();

__END__

=encoding utf-8

=head1 README

This is a Github project.  The latest version is listed as a tag in the project.

